"""Structural checks on `docs/`, so documentation cannot drift silently.

Documentation in this repo is written by humans and by coding agents. Agents
append; nothing prunes. The taxonomy in `docs/README.md` gives every paragraph
exactly one home, and this script is what makes that placement binding rather
than advisory.

Run via pre-commit and via pytest in CI. Exits non-zero on any failure, printing
one line per problem. Size and staleness are warnings only: a gate must depend on
the change under review, and neither of those does.

--------------------------------------------------------------------------------
ADAPTING THIS FILE TO A PROJECT

Everything project-specific is in the CONFIGURATION block below. Read it top to
bottom before wiring the script in; most projects change three things:

  1. FRENCH_MARKERS / FRENCH_THRESHOLD - delete both, and the `check_language`
     call, if the project has no language rule. Replace the marker list if the
     second language is not French.
  2. PROSE_CAP - the warning thresholds.
  3. FILLER - the banned openers your own conventions doc names.

Do NOT add a hard size cap or fail on `stale_after`. See the skill's
references/pitfalls.md for what that costs.

Requires PyYAML. If the project has no Python runtime, port the rules rather
than adding one - the rule set matters, this implementation does not.
--------------------------------------------------------------------------------
"""

from __future__ import annotations

import datetime as dt
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

# ============================== CONFIGURATION ==============================

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"

#: Maintained folders. `type` in a doc's frontmatter must equal its folder name.
MAINTAINED = ("explanation", "how-to", "reference", "conventions")
#: Dated, append-only records. Exempt from the prose and size checks.
JOURNAL = "journal"

#: The name of a folder's own index file, at the root of `docs/` and inside a
#: journal category.
INDEX_NAME = "README.md"
#: Files at the root of `docs/` that are not quadrant docs.
ROOT_ALLOWED = {INDEX_NAME, "BACKLOG.md"}

VALID_AUDIENCE = {"human", "agent"}
VALID_STATUS = {"draft", "stable", "deprecated"}

PROSE_CAP = {"reference": 250}
PROSE_CAP_DEFAULT = 150

#: Past-tense incident narration. Belongs in `journal/solutions/`, never in a
#: maintained doc - see `docs/conventions/documentation.md`.
INCIDENT_MARKERS = (
    r"\bused to (?:be|have|do|fire|return|inject|strip|pass|show|print|ask|call|"
    r"reorder|crash|hold|live|work|happen|contain|produce|move|wait)\b",
    r"\bpreviously,\b",
    r"\bwas tried\b",
    r"\bwe tried\b",
    r"\battempts? (?:failed|out of)\b",
    r"\bbefore this fix\b",
    r"\bearlier version\b",
    r"\b\d+ (?:attempts?|tries|runs?) out of \d+\b",
    r"\b\d+ (?:essais?|tentatives?) sur \d+\b",
    r"\bturned out to be false\b",
)

#: Filler openers banned by `conventions/documentation.md`.
FILLER = (
    r"il est important de noter que",
    r"on notera que",
    r"il convient de noter",
    r"it is worth mentioning that",
    r"it should be noted that",
    r"it is important to note that",
    r"as mentioned previously",
)

#: French function words. Several of these on one line means the line is French.
#: Scored rather than matched singly: words like "la" and "des" occur in English
#: prose, so one hit proves nothing while four hits are conclusive. Business
#: vocabulary that keeps its French name in English (dossier, apport, VEFA,
#: primo-accedant) is deliberately absent.
FRENCH_MARKERS = re.compile(
    r"\b(?:le|la|les|une?|des|du|dans|pour|avec|sur|que|qui|donc|mais|est|sont|"
    r"cette|ces|ce|il|elle|nous|vous|leur|tout|toute|alors|ainsi|quand|lorsque|"
    r"parce|puisque|entre|chaque|aucune?|jamais|toujours|pas|ne|se|son|sa|ses|"
    r"comme|plut\u00f4t|d\u00e9j\u00e0|encore|aussi)\b",
    re.I,
)
#: How many French markers on one line before it is called French prose.
FRENCH_THRESHOLD = 4

KEBAB = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*\.(?:md|yaml)$")
ADR_NAME = re.compile(r"^\d{4}-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
#: Set to None if the project has no generated backlog mirror.
GENERATED_BACKLOG_HEADER = "<!-- GENERATED by scripts/sync_backlog.py"

# ============================ END CONFIGURATION ============================


@dataclass
class Problem:
    """One failure or warning, tied to a file."""

    path: Path
    message: str
    warning: bool = False

    def render(self) -> str:
        """Return the one-line report for this problem."""
        rel = self.path.relative_to(REPO_ROOT)
        tag = "warn" if self.warning else "FAIL"
        return f"{tag}  {rel}: {self.message}"


def split_frontmatter(text: str) -> tuple[dict | None, str]:
    """Return the parsed YAML frontmatter and the body that follows it."""
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---\n", 3)
    if end == -1:
        return None, text
    raw = text[4:end]
    body = text[end + 5 :]
    try:
        parsed = yaml.safe_load(raw)
    except yaml.YAMLError:
        return None, body
    return (parsed if isinstance(parsed, dict) else None), body


def strip_code(body: str) -> str:
    """Return the body with fenced code blocks and inline code removed."""
    without_fences = re.sub(r"^[ \t]*```.*?^[ \t]*```", "", body, flags=re.S | re.M)
    return re.sub(r"`[^`\n]*`", "", without_fences)


def prose_lines(body: str) -> int:
    """Count body lines that are prose - not code, not a table, not a heading."""
    count = 0
    in_fence = False
    for line in body.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "|", ">", "---")):
            continue
        count += 1
    return count


def check_frontmatter(path: Path, meta: dict | None, folder: str) -> list[Problem]:
    """Check a maintained doc's frontmatter against the documented schema."""
    if meta is None:
        return [Problem(path, "missing or unparseable YAML frontmatter")]
    problems = [
        Problem(path, f"frontmatter missing `{key}`")
        for key in ("title", "type", "audience", "status", "stale_after")
        if key not in meta
    ]
    if (declared := meta.get("type")) and declared != folder:
        problems.append(
            Problem(path, f"`type: {declared}` does not match its folder `{folder}/`")
        )
    problems.extend(check_enums(path, meta))
    problems.extend(check_expiry(path, meta.get("stale_after")))
    return problems


def check_enums(path: Path, meta: dict) -> list[Problem]:
    """Check the `audience` and `status` values against their vocabularies."""
    problems: list[Problem] = []
    audience = meta.get("audience")
    if audience is not None:
        values = audience if isinstance(audience, list) else [audience]
        if bad := set(values) - VALID_AUDIENCE:
            problems.append(Problem(path, f"invalid audience {sorted(bad)}"))
    if (status := meta.get("status")) and status not in VALID_STATUS:
        problems.append(Problem(path, f"invalid status `{status}`"))
    return problems


def check_expiry(path: Path, expiry: object) -> list[Problem]:
    """Check that `stale_after` is an ISO date still in the future."""
    if expiry is None:
        return []
    if isinstance(expiry, dt.datetime):
        expiry = expiry.date()  # YAML parses `2027-03-02 00:00` as a datetime
    elif not isinstance(expiry, dt.date):
        return [Problem(path, "`stale_after` is not an ISO date")]
    if expiry < dt.date.today():
        message = f"`stale_after: {expiry}` has passed - review or re-date it"
        return [Problem(path, message, warning=True)]
    return []


def check_prose(path: Path, body: str, folder: str, offset: int = 0) -> list[Problem]:
    """Check language, incident narration, filler and size in a maintained doc.

    `offset` is the number of frontmatter lines above `body`, so reported line
    numbers match the file rather than the body.
    """
    problems = check_language(path, body, offset)
    plain = strip_code(body)

    if folder in ("reference", "conventions"):
        for marker in INCIDENT_MARKERS:
            if hit := re.search(marker, plain, re.I):
                problems.append(
                    Problem(
                        path,
                        f"incident narration {hit.group(0)!r} - move it to "
                        "journal/solutions/ and leave the rule with a link",
                    )
                )
    for marker in FILLER:
        if hit := re.search(marker, plain, re.I):
            problems.append(Problem(path, f"filler phrase {hit.group(0)!r}"))

    cap = PROSE_CAP.get(folder, PROSE_CAP_DEFAULT)
    if (count := prose_lines(body)) > cap:
        problems.append(
            Problem(
                path, f"{count} prose lines, over the {cap} guideline", warning=True
            )
        )
    return problems


def check_language(path: Path, body: str, offset: int) -> list[Problem]:
    """Report the first line outside a code fence that reads as French."""
    in_fence = False
    for number, raw in enumerate(body.splitlines(), start=1 + offset):
        if raw.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        line = re.sub(r"`[^`\n]*`", "", raw)
        hits = {hit.lower() for hit in FRENCH_MARKERS.findall(line)}
        if len(hits) >= FRENCH_THRESHOLD:
            return [Problem(path, f"line {number} is French: {sorted(hits)[:6]}")]
    return []


def check_journal_entry(path: Path, rel: Path) -> list[Problem]:
    """Check an append-only journal entry: its links, and an ADR's filename."""
    problems = check_links(path)
    is_decision = len(rel.parts) >= 2 and rel.parts[1] == "decisions"
    if is_decision and rel.name != INDEX_NAME and not ADR_NAME.match(rel.name):
        problems.append(Problem(path, "ADR name must be `NNNN-with-dashes.md`"))
    return problems


def opens_with_scope(body: str) -> bool:
    """Return whether the body's first paragraph after the H1 is a `Scope:` line."""
    blocks = [block for block in body.split("\n\n") if block.strip()]
    return any("**Scope:" in block for block in blocks[:2])


def check_links(path: Path) -> list[Problem]:
    """Check that every relative markdown link resolves on disk."""
    problems: list[Problem] = []
    text = path.read_text(encoding="utf-8")
    for target in re.findall(r"\]\(([^)\s#]+\.(?:md|yaml))(?:#[^)]*)?\)", text):
        if target.startswith(("http://", "https://", "/")):
            continue
        if not (path.parent / target).exists():
            problems.append(Problem(path, f"broken link -> {target}"))
    return problems


def check_index(index_text: str, maintained: list[Path]) -> list[Problem]:
    """Check that every maintained doc is listed in `docs/README.md`."""
    return [
        Problem(path, "not listed in docs/README.md")
        for path in maintained
        if str(path.relative_to(DOCS)) not in index_text
    ]


def check_backlog(path: Path) -> list[Problem]:
    """Check that BACKLOG.md still carries its generated header."""
    if not path.exists():
        return []
    if (
        not path.read_text(encoding="utf-8")
        .lstrip()
        .startswith(GENERATED_BACKLOG_HEADER)
    ):
        return [
            Problem(path, "missing the generated header - it must not be hand-edited")
        ]
    return []


def check_maintained_doc(path: Path, folder: str) -> list[Problem]:
    """Run every check that applies to one maintained markdown doc."""
    problems: list[Problem] = []
    if not KEBAB.match(path.name):
        problems.append(Problem(path, "filename must be kebab-case"))
    problems.extend(check_links(path))

    text = path.read_text(encoding="utf-8")
    meta, body = split_frontmatter(text)
    offset = len(text.splitlines()) - len(body.splitlines())
    problems.extend(check_frontmatter(path, meta, folder))
    problems.extend(check_prose(path, body, folder, offset))

    if folder == "conventions" and not opens_with_scope(body):
        problems.append(
            Problem(path, "a conventions/ file must open with a `**Scope:` line")
        )
    return problems


def classify(path: Path, rel: Path) -> tuple[list[Problem], bool]:
    """Route one file to its checks, and say whether it is a maintained doc."""
    parts = rel.parts
    if len(parts) == 1:
        if rel.name not in ROOT_ALLOWED:
            return [
                Problem(path, "loose file at the root of docs/ - it needs a folder")
            ], False
        return [], False

    folder = parts[0]
    if folder == JOURNAL:
        return check_journal_entry(path, rel), False
    if folder not in MAINTAINED:
        return [Problem(path, f"unknown folder `{folder}/`")], False
    if path.suffix == ".yaml":
        return check_links(path), False
    return check_maintained_doc(path, folder), True


def check_docs() -> list[Problem]:
    """Run every documentation check and return the problems found."""
    problems: list[Problem] = []
    maintained: list[Path] = []

    for path in sorted(DOCS.rglob("*.md")) + sorted(DOCS.rglob("*.yaml")):
        found, is_maintained = classify(path, path.relative_to(DOCS))
        problems.extend(found)
        if is_maintained:
            maintained.append(path)

    index = DOCS / INDEX_NAME
    if not index.exists():
        problems.append(Problem(DOCS, f"docs/{INDEX_NAME} is missing"))
    else:
        problems.extend(check_index(index.read_text(encoding="utf-8"), maintained))
        problems.extend(check_links(index))

    problems.extend(check_backlog(DOCS / "BACKLOG.md"))
    return problems


def main() -> int:
    """Print every problem and return the process exit code."""
    problems = check_docs()
    for problem in sorted(problems, key=lambda p: (p.warning, str(p.path))):
        # This is a CLI check reporting to a terminal, not application logging.
        print(problem.render())  # noqa: T201
    failures = [p for p in problems if not p.warning]
    if failures:
        print(f"\n{len(failures)} documentation problem(s). See docs/README.md.")  # noqa: T201
        return 1
    print("docs/ structure OK")  # noqa: T201
    return 0


if __name__ == "__main__":
    sys.exit(main())
