#!/usr/bin/env bash
# Reject a hand edit to docs/BACKLOG.md.
#
# Ship this only alongside a backlog mirror - see the skill's
# references/backlog.md. The file mirrors the GitHub issues labelled `backlog`
# and is written by scripts/sync_backlog.py. A hand edit is silently discarded by
# the next regeneration, so it is caught here instead.
#
# "Was it hand-edited?" is answered by regenerating and comparing, not by
# looking at what else is staged: a legitimate `make sync-backlog` after an
# issue changed touches this file and nothing else.
#
# ONE excuse to pass without answering: the issue tracker is unreachable. Being
# offline must not block a commit. Everything else - no interpreter, a crashing
# generator, a missing file - is a real failure and exits non-zero, because a
# hook that reports every error as success is not a gate.
set -uo pipefail

BACKLOG=docs/BACKLOG.md
# Adapt to the project's runner. Whatever it is, a commit hook must not
# re-resolve a lockfile or run a build script: use the environment already
# installed. With uv that is `uv run --no-sync --no-build python`.
PYTHON=${PYTHON:-python3}

# -F: a literal match. Without it, the dot in the filename is a wildcard.
git diff --cached --name-only | grep -qxF "$BACKLOG" || exit 0

if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  echo "note: cannot reach GitHub, skipping the $BACKLOG check." >&2
  exit 0
fi

if ! command -v "$PYTHON" >/dev/null 2>&1; then
  echo "error: $PYTHON not found. Set PYTHON=... to the project's runner." >&2
  exit 1
fi

# Staged for deletion, or otherwise gone: there is nothing to compare against,
# and the generator would recreate it. Removing the mirror is a deliberate act
# that removes its generator and its rules too, not a commit-time surprise.
if [[ ! -f "$BACKLOG" ]]; then
  echo "error: $BACKLOG is staged but missing from the working tree." >&2
  echo "Removing the mirror means removing its generator and its rules too." >&2
  exit 1
fi

before=$(cat "$BACKLOG")

if ! output=$("$PYTHON" scripts/sync_backlog.py 2>&1); then
  echo "error: could not regenerate $BACKLOG." >&2
  echo "$output" >&2
  exit 1
fi

if [[ "$before" == "$(cat "$BACKLOG")" ]]; then
  exit 0
fi

cat >&2 <<MSG
$BACKLOG does not match the GitHub issues labelled \`backlog\`.

It is generated by scripts/sync_backlog.py - do not edit it by hand. The file has
just been regenerated in place, so \`git add $BACKLOG\` and commit again.

To change the backlog, open or close an issue with the \`backlog\` label.
See docs/conventions/documentation.md.
MSG
exit 1
