#!/usr/bin/env bash
# Reject a hand edit to docs/BACKLOG.md.
#
# Ship this only alongside a backlog mirror - see the skill's
# references/backlog.md. The file mirrors the GitHub issues labelled `backlog`
# and is written by scripts/sync_backlog.py. A hand edit is silently discarded by
# the next regeneration, so it is caught here instead.
#
# "Was it hand-edited?" is answered by regenerating and comparing, not by
# looking at what else is staged: a legitimate `make sync-backlog` after an
# issue changed touches this file and nothing else. Without the issue tracker
# reachable the question cannot be answered, so the hook passes rather than
# blocking a commit for being offline.
set -uo pipefail

staged=$(git diff --cached --name-only)
grep -qx "docs/BACKLOG.md" <<<"$staged" || exit 0

if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  echo "note: cannot reach GitHub, skipping the docs/BACKLOG.md check." >&2
  exit 0
fi

before=$(cat docs/BACKLOG.md)
# Adapt the runner to the project. Whatever it is, a commit hook must not
# re-resolve a lockfile or run a build script: use the environment that is
# already installed. With uv, that is `uv run --no-sync --no-build`.
if ! python scripts/sync_backlog.py >/dev/null 2>&1; then
  echo "note: could not regenerate docs/BACKLOG.md, skipping the check." >&2
  exit 0
fi

if [[ "$before" == "$(cat docs/BACKLOG.md)" ]]; then
  exit 0
fi

cat >&2 <<'MSG'
docs/BACKLOG.md does not match the GitHub issues labelled `backlog`.

It is generated by scripts/sync_backlog.py - do not edit it by hand. The file has
just been regenerated in place, so `git add docs/BACKLOG.md` and commit again.

To change the backlog, open or close an issue with the `backlog` label.
See docs/conventions/documentation.md.
MSG
exit 1
