"""Regenerate `docs/BACKLOG.md` from the GitHub issues carrying a label.

Ship this ONLY when a workflow can push to the default branch. The mirror exists
so an agent reading the repository sees the unbuilt work with no tool call and no
network; a mirror somebody has to remember to refresh is a cache of one command,
and not worth the apparatus. The skill's references/backlog.md has the one
question that decides it, and the Action that keeps this fresh.

The file is generated, never hand-edited: `check_docs.py` fails when the header
is missing, and a pre-commit hook rejects a hand edit by regenerating and
comparing.

Rows are ordered by issue number, so a re-run with no upstream change produces
no diff. Without that, every run diffs for nothing and the mirror becomes noise.

--------------------------------------------------------------------------------
ADAPTING THIS FILE

Everything project-specific is in the CONFIGURATION block. Requires the `gh` CLI,
authenticated. Uses `loguru` if present and the standard library otherwise, so it
drops into a project either way.
--------------------------------------------------------------------------------
"""

from __future__ import annotations

import json
import logging
import subprocess
import sys
from pathlib import Path

# Messages below are f-strings rather than lazy `%s`/`{}` arguments: loguru and
# the standard library disagree on the placeholder, and a pre-rendered message is
# the only form both accept.
try:
    from loguru import logger
except ImportError:  # a project without loguru still gets readable output
    logging.basicConfig(format="%(levelname)s %(message)s", level=logging.INFO)
    logger = logging.getLogger(__name__)  # type: ignore[assignment]

# ============================== CONFIGURATION ==============================

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "BACKLOG.md"
#: A file that marks REPO_ROOT as the skill rather than an adopting project. The
#: script resolves its output relative to itself, so running it in place writes
#: into the skill - which happened. Set to None once copied, or leave it: an
#: adopting project has no SKILL.md at its root.
NOT_A_PROJECT_MARKER = "SKILL.md"

#: Only issues carrying this label reach the backlog. Everything else - bug
#: reports, questions, support - stays out.
BACKLOG_LABEL = "backlog"
#: Labels prefixed with this name the area of the codebase an item touches. A
#: title alone does not tell an agent which module to open.
AREA_PREFIX = "area:"
#: What the Area column shows when an issue carries no `area:*` label.
NO_AREA = "—"
#: One request's page size. Hitting it exactly means the mirror is truncated, so
#: it is logged rather than silently dropping rows.
PAGE_SIZE = 500
#: The refresh command named in the generated header.
REFRESH_COMMAND = "make sync-backlog"

HEADER = f"""<!-- GENERATED by scripts/sync_backlog.py - DO NOT EDIT.
     Open or close a GitHub issue with the `{BACKLOG_LABEL}` label instead, then run
     `{REFRESH_COMMAND}`. See docs/conventions/documentation.md. -->

# Backlog

Work that is known, wanted, and not built. One row per open GitHub issue labelled
`{BACKLOG_LABEL}`.

This file is a mirror, not the source. To add an item, open an issue and label it
`{BACKLOG_LABEL}` plus an `{AREA_PREFIX}*` label. To remove one, close the issue.

Never write a TODO or a "future work" section into a doc under `docs/` - nothing prunes
those.
"""

TABLE_HEAD = "\n| # | Item | Area |\n| --- | --- | --- |\n"
#: One row. Change it and TABLE_HEAD together - they describe the same table, and
#: a row format hidden in the code below could not follow a changed heading.
TABLE_ROW = "| [#{number}]({url}) | {title} | {area} |\n"
EMPTY = "\nNothing open.\n"

# ============================ END CONFIGURATION ============================


class Truncated(RuntimeError):
    """The tracker returned a full page, so the mirror would be incomplete."""


def fetch_issues() -> list[dict]:
    """Return the open labelled issues, ordered by issue number."""
    result = subprocess.run(
        [
            "gh",
            "issue",
            "list",
            "--label",
            BACKLOG_LABEL,
            "--state",
            "open",
            "--limit",
            str(PAGE_SIZE),
            "--json",
            "number,title,url,labels",
        ],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT,
    )
    issues = json.loads(result.stdout or "[]")
    if len(issues) >= PAGE_SIZE:
        # Not a warning. A stale mirror is an out-of-date convenience; a silently
        # truncated one is a wrong answer, and the rows it drops are exactly the
        # ones nobody is looking at.
        raise Truncated(
            f"the tracker returned at least {PAGE_SIZE} issues, so the mirror "
            f"would be incomplete. Raise PAGE_SIZE, or narrow the label."
        )
    return sorted(issues, key=lambda issue: issue["number"])


def area_of(issue: dict) -> str:
    """Return the issue's areas, from its `area:*` labels."""
    areas = sorted(
        label["name"].removeprefix(AREA_PREFIX)
        for label in issue.get("labels", [])
        if label["name"].startswith(AREA_PREFIX)
    )
    # A label is as attacker-controlled as a title wherever anyone may create
    # one, and it lands in a table cell just the same.
    return cell(", ".join(areas)) if areas else NO_AREA


def cell(title: str) -> str:
    """Return an issue title that is safe to place in a markdown table cell.

    An issue title is written by anyone who can open an issue, and it is mirrored
    into a file that agents read as repository truth. A title may also be edited
    *after* a maintainer applied the label, so the text a triager approved is not
    necessarily the text arriving here.

    What is neutralised is anything that changes the rendered *structure* rather
    than the words:

    * a newline, which ends the table and lets the rest become markdown of its
      own - a heading, a list, an instruction addressed to an agent;
    * `|`, which adds a column;
    * `<` and `>`, so no HTML tag renders (this also disarms `<!--` and `-->`,
      which could close the generated header);
    * `[` and `]`, so a title cannot become a link pointing somewhere else.

    The trade-off, stated: intentional formatting in a title is shown literally.
    A title reading `use [the API]` renders with its brackets. That is the right
    way round - a mirror reproduces what the tracker says, and the tracker's
    titles are text, not markup.
    """
    collapsed = " ".join(title.split())
    for source, target in (
        ("&", "&amp;"),  # first, or it would double-escape the others
        ("|", r"\|"),
        ("<", "&lt;"),
        (">", "&gt;"),
        ("[", r"\["),
        ("]", r"\]"),
    ):
        collapsed = collapsed.replace(source, target)
    return collapsed


def render(issues: list[dict]) -> str:
    """Return the full contents of the backlog mirror."""
    if not issues:
        return HEADER + EMPTY
    rows = "".join(
        TABLE_ROW.format(
            number=issue["number"],
            url=issue["url"],
            title=cell(issue["title"]),
            area=area_of(issue),
        )
        for issue in issues
    )
    return HEADER + TABLE_HEAD + rows


def main() -> int:
    """Regenerate the backlog file and report whether it changed."""
    if NOT_A_PROJECT_MARKER and (REPO_ROOT / NOT_A_PROJECT_MARKER).exists():
        logger.error(
            f"{REPO_ROOT} holds a {NOT_A_PROJECT_MARKER}, so this is the skill's "
            "own copy, not a project. Copy the script into the project first."
        )
        return 1

    try:
        issues = fetch_issues()
    except FileNotFoundError:
        logger.error("`gh` is not installed - cannot reach the issue tracker.")
        return 1
    except subprocess.CalledProcessError as error:
        logger.error(f"`gh issue list` failed: {(error.stderr or '').strip()}")
        return 1
    except Truncated as error:
        logger.error(f"Refusing to write a partial mirror: {error}")
        return 1

    rendered = render(issues)
    previous = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")

    if previous == rendered:
        logger.info(f"{OUTPUT_PATH.name} already up to date ({len(issues)} item(s)).")
    else:
        logger.info(f"Wrote {OUTPUT_PATH} with {len(issues)} item(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
