"""Tests for `check_backlog_staging.sh`.

The hook is the only thing standing between a hand-edited mirror and a commit,
and every one of its exits used to be `exit 0`. A gate that reports every error
as success is not a gate, so each of the five paths is pinned here.

Every test builds a throwaway git repo and a fake `PATH`, so nothing touches the
real `gh` or the real tracker.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

HOOK = Path(__file__).resolve().parent / "check_backlog_staging.sh"
GENERATED = "<!-- GENERATED by scripts/sync_backlog.py -->\n\n# Backlog\n"


def executable(path: Path, body: str) -> None:
    """Write a fake command and make it runnable."""
    path.write_text(body, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """Return a git repo with a staged mirror, a fake `gh`, and a fake generator."""
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    executable(bin_dir / "gh", "#!/bin/sh\nexit 0\n")  # `gh auth status` succeeds
    for name in ("git", "grep", "cat", "python3", "sh", "bash", "env"):
        if found := shutil.which(name):
            (bin_dir / name).symlink_to(found)

    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "BACKLOG.md").write_text(GENERATED, encoding="utf-8")
    scripts = tmp_path / "scripts"
    scripts.mkdir()
    # The default generator rewrites the same bytes: the mirror is in sync.
    executable(
        scripts / "sync_backlog.py",
        "#!/usr/bin/env python3\nimport pathlib\n"
        f"pathlib.Path('docs/BACKLOG.md').write_text({GENERATED!r})\n",
    )
    subprocess.run(["git", "add", "docs/BACKLOG.md"], cwd=tmp_path, check=True)
    return tmp_path


def run(repo: Path, **env: str) -> subprocess.CompletedProcess:
    """Run the hook in `repo` with only the fake `PATH` visible."""
    return subprocess.run(
        ["bash", str(HOOK)],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,  # the exit code is what every test here asserts on
        env={
            "PATH": f"{repo / 'bin'}:{os.environ.get('PATH', '')}",
            "HOME": str(repo),
            **env,
        },
    )


def test_it_passes_when_the_mirror_is_not_staged(repo: Path) -> None:
    """The path every unrelated commit takes. It must not reach `gh`."""
    subprocess.run(["git", "reset", "-q"], cwd=repo, check=True)
    result = run(repo)
    assert result.returncode == 0, result.stderr
    assert result.stderr == ""


def test_it_passes_when_the_staged_mirror_matches_the_tracker(repo: Path) -> None:
    """A legitimate refresh: regenerating changes nothing."""
    result = run(repo)
    assert result.returncode == 0, result.stderr


def test_it_fails_on_a_hand_edit(repo: Path) -> None:
    """The whole point: an edit the next regeneration would silently discard."""
    (repo / "docs" / "BACKLOG.md").write_text(
        GENERATED + "\n- something I typed\n", encoding="utf-8"
    )
    subprocess.run(["git", "add", "docs/BACKLOG.md"], cwd=repo, check=True)
    result = run(repo)
    assert result.returncode == 1
    assert "does not match the GitHub issues" in result.stderr


def test_it_passes_when_github_is_unreachable(repo: Path) -> None:
    """The one excuse: being offline must not block a commit."""
    executable(repo / "bin" / "gh", "#!/bin/sh\nexit 1\n")  # auth status fails
    result = run(repo)
    assert result.returncode == 0, result.stderr
    assert "cannot reach GitHub" in result.stderr


def test_it_fails_when_gh_is_absent_but_reports_why(repo: Path) -> None:
    """No `gh` at all is indistinguishable from offline, so it still passes."""
    (repo / "bin" / "gh").unlink()
    result = run(repo)
    assert result.returncode == 0, result.stderr
    assert "cannot reach GitHub" in result.stderr


def test_it_fails_when_the_interpreter_is_missing(repo: Path) -> None:
    """`python` vs `python3` made this branch fire on every macOS commit."""
    result = run(repo, PYTHON="python-that-does-not-exist")
    assert result.returncode == 1
    assert "not found" in result.stderr


def test_it_fails_when_the_generator_crashes(repo: Path) -> None:
    """A broken generator is a real failure, not a reason to wave the commit on."""
    executable(
        repo / "scripts" / "sync_backlog.py",
        "#!/usr/bin/env python3\nimport sys\nprint('boom', file=sys.stderr)\n"
        "sys.exit(2)\n",
    )
    result = run(repo)
    assert result.returncode == 1
    assert "could not regenerate" in result.stderr
    assert "boom" in result.stderr


def test_it_fails_when_the_mirror_is_staged_for_deletion(repo: Path) -> None:
    """Removing the mirror is deliberate work, not a commit-time surprise.

    A deletion is only stageable once the file has a commit behind it - before
    that, removing a newly added file just drops it from the index.
    """
    commit = ["git", "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "x"]
    subprocess.run(commit, cwd=repo, check=True)
    (repo / "docs" / "BACKLOG.md").unlink()
    subprocess.run(["git", "add", "-A", "docs/BACKLOG.md"], cwd=repo, check=True)
    result = run(repo)
    assert result.returncode == 1
    assert "missing from the working tree" in result.stderr


def test_a_similarly_named_file_does_not_trigger_it(repo: Path) -> None:
    """`grep -qx` without `-F` treats the dot as a wildcard, matching BACKLOGxmd."""
    subprocess.run(["git", "reset", "-q"], cwd=repo, check=True)
    decoy = repo / "docs" / "BACKLOGxmd"
    decoy.write_text("not the mirror\n", encoding="utf-8")
    subprocess.run(["git", "add", str(decoy)], cwd=repo, check=True)
    result = run(repo)
    assert result.returncode == 0, result.stderr
    assert result.stderr == ""
